#!/usr/bin/env bash

basedir="$(cd "$(dirname "$0")/.." && pwd)"

rm -f "${basedir}/snippets"/**/*

sed_commands=()
# shellcheck disable=SC2016
sed_commands+=( '0,/{{ year }}/s/{{ year }}/${1:`(decoded-time-year (decode-time))`}/' )
# shellcheck disable=SC2016
sed_commands+=( '0,/{{ organization }}/s/{{ organization }}/${2:`user-full-name`}/' )
# shellcheck disable=SC2016
sed_commands+=( 's/{{ year }}/$1/g' )
# shellcheck disable=SC2016
sed_commands+=( 's/{{ organization }}/$2/g' )
# shellcheck disable=SC2016
sed_commands+=( 's/{{ project }}/$3/g' )

find "${basedir}/license-templates/templates" \
  -type f \
  -name '*.txt' -a ! -name '*-header.txt' |
  while read -r file; do
    name="${file##*/}"
    name="${name%.txt}"
    key="${name//_/}"
    name="${name//_/ }"
    condition='(string-equal base-name "LICENSE")'
    if [[ "$name" == 'mit' ]]; then
      condition="(or (string-equal base-name \"LICENSE-MIT\") ${condition})"
    fi
    condition="(let* ((base-name (and buffer-file-name (file-name-nondirectory buffer-file-name)))) ${condition})"

    {
      cat <<EOM
# -*- mode: snippet -*-
# name: ${name}
# key: ${key}
# condition: ${condition}
# --

EOM
      sed -e "$(IFS=';'; echo "${sed_commands[*]}")" "$file"
    } >"${basedir}/snippets/text-mode/${key}"
  done
